"""
gsheets.py — read raw data FROM a private Google Sheet and write the finished
report BACK to it, using a Google service-account key.

Setup (free):
  1. Google Cloud console → create a project → enable the **Google Sheets API**.
  2. Create a **service account** → create a JSON key → download it.
  3. Open your Google Sheet → Share → add the service account's email
     (the `client_email` in the JSON) as **Editor**.
  4. Put the data in worksheets/tabs named or columned so each is detectable:
       bookings tab  (has `booking_id`), partners tab (`onboard_date`/`primary_category`),
       leads tab     (`lead_id`/`stage`).

The app then reads those tabs, runs the same cleaning → decisions → charts
pipeline, and (on demand) writes a **"BD Report"** tab back with the KPIs,
recruitment actions, alerts, and memo.

CLI to populate a test sheet from the local sample files:
    python gsheets.py upload --url <sheet_url> --creds key.json
"""

import json
import sys

import pandas as pd

# service-account scope: read + write spreadsheets (no Drive scope needed when
# opening by URL/key and adding worksheets via the Sheets API).
SCOPES = ["https://www.googleapis.com/auth/spreadsheets"]

REPORT_TAB = "BD Report"
REPORT_WIDTH = 7  # columns the report block uses (recruitment table is widest)


# ----------------------------------------------------------------------------
# auth + open
# ----------------------------------------------------------------------------
def connect(sa_info):
    """sa_info: a dict (parsed service-account JSON) OR a path to the JSON file."""
    import gspread
    from google.oauth2.service_account import Credentials

    if isinstance(sa_info, str):
        with open(sa_info, "r", encoding="utf-8") as f:
            sa_info = json.load(f)
    creds = Credentials.from_service_account_info(sa_info, scopes=SCOPES)
    return gspread.authorize(creds)


def service_account_email(sa_info):
    if isinstance(sa_info, str):
        with open(sa_info, "r", encoding="utf-8") as f:
            sa_info = json.load(f)
    return sa_info.get("client_email", "(unknown)")


def _open(client, url_or_key):
    s = str(url_or_key).strip()
    if s.startswith("http"):
        return client.open_by_url(s)
    return client.open_by_key(s)


# ----------------------------------------------------------------------------
# read
# ----------------------------------------------------------------------------
def read_workbook(client, url_or_key):
    """Read every worksheet, auto-detect bookings/partners/leads by columns."""
    from ingest import _detect_kind

    sh = _open(client, url_or_key)
    raw = {"bookings": None, "partners": None, "leads": None}
    found = []
    for ws in sh.worksheets():
        records = ws.get_all_records()  # uses the header row as keys
        if not records:
            found.append(f"{ws.title} → empty (skipped)")
            continue
        df = pd.DataFrame(records)
        kind = _detect_kind(df)
        if kind in raw and raw[kind] is None:
            raw[kind] = df
            found.append(f"{ws.title} → {kind} ({len(df)} rows)")
        else:
            found.append(f"{ws.title} → {kind} (ignored)")
    return raw, found


def load_from_gsheet(client, url_or_key):
    """Read + clean + join straight into the app's data structure + merge log."""
    from ingest import _clean_and_join, _build_log

    raw, found = read_workbook(client, url_or_key)
    data, cleaning_logs = _clean_and_join(raw)
    merge_log = _build_log(data, found, cleaning_logs)
    merge_log["source"] = "Google Sheets"
    return data, merge_log


# ----------------------------------------------------------------------------
# write report back
# ----------------------------------------------------------------------------
def _pad(row, width=REPORT_WIDTH):
    row = [("" if v is None else v) for v in row]
    return row + [""] * (width - len(row))


def report_rows(kpis, gap_table, alerts, memo, generated_at=""):
    """Pure builder → a rectangular 2D list of cells. Testable without the API."""
    from insights import inr

    rows = []
    rows.append(_pad(["BD PERFORMANCE & ACTION REPORT"]))
    rows.append(_pad([f"Generated: {generated_at}" if generated_at else "Generated by BD Action Report"]))
    rows.append(_pad([]))

    # KPIs
    rows.append(_pad(["KEY PERFORMANCE INDICATORS"]))
    rows.append(_pad(["GMV", inr(kpis["gmv"]),
                      "Bookings", f"{kpis['total_bookings']:,}",
                      "AOV", inr(kpis["aov"])]))
    rows.append(_pad(["Active partners", kpis["active_partners"],
                      "Completion", f"{kpis['completion_rate']*100:.0f}%",
                      "₹/week at risk", inr(kpis["revenue_at_risk_per_week"])]))
    rows.append(_pad([]))

    # recruitment table
    rows.append(_pad(["RECOMMENDED RECRUITMENT (ranked by ₹/week at risk)"]))
    rows.append(_pad(["City", "Category", "Active partners", "Cancel %",
                      "WoW demand", "Recruit", "₹/week at risk"]))
    under = pd.DataFrame()
    if gap_table is not None and len(gap_table):
        under = gap_table[gap_table["gap_flag"] == "UNDERSUPPLIED"].head(15)
    if len(under):
        for _, r in under.iterrows():
            rows.append(_pad([
                r["city"], r["service_category"], int(r["active_partners"]),
                f"{r['cancel_rate']*100:.0f}%", f"{r['wow_growth']*100:+.0f}%",
                int(r["recommended_partner_adds"]), inr(r["est_revenue_at_risk_per_week"]),
            ]))
    else:
        rows.append(_pad(["No critical undersupply this week."]))
    rows.append(_pad([]))

    # alerts
    rows.append(_pad(["ALERTS"]))
    if alerts:
        for a in alerts[:15]:
            rows.append(_pad([a.get("severity", "").upper(), a.get("text", "")]))
    else:
        rows.append(_pad(["No anomalies beyond thresholds this week."]))
    rows.append(_pad([]))

    # memo
    rows.append(_pad(["LEADERSHIP MEMO"]))
    for line in (memo or "").splitlines():
        clean = line.replace("###", "").replace("**", "").rstrip()
        if clean.strip():
            rows.append(_pad([clean]))

    return rows


def write_report(client, url_or_key, kpis, gap_table, alerts, memo,
                 tab=REPORT_TAB, generated_at=""):
    """Create/clear the report tab and write the report block. Returns the tab URL."""
    import gspread

    sh = _open(client, url_or_key)
    rows = report_rows(kpis, gap_table, alerts, memo, generated_at)
    n_rows = max(len(rows) + 5, 50)

    try:
        ws = sh.worksheet(tab)
        ws.clear()
        ws.resize(rows=n_rows, cols=REPORT_WIDTH)
    except gspread.WorksheetNotFound:
        ws = sh.add_worksheet(title=tab, rows=n_rows, cols=REPORT_WIDTH)

    ws.update(range_name="A1", values=rows)

    # light formatting on section headers (best-effort; never fatal)
    try:
        ws.format("A1:G1", {"textFormat": {"bold": True, "fontSize": 14}})
    except Exception:
        pass

    return f"https://docs.google.com/spreadsheets/d/{sh.id}/edit#gid={ws.id}"


# ----------------------------------------------------------------------------
# push raw sample data to a sheet (to set up a test workbook)
# ----------------------------------------------------------------------------
def push_dataframes(client, url_or_key, frames):
    """frames: {"bookings": df, "partners": df, "leads": df} -> one tab each."""
    import gspread

    sh = _open(client, url_or_key)
    written = []
    for name, df in frames.items():
        if df is None or len(df) == 0:
            continue
        df = df.copy()
        for c in df.columns:
            df[c] = df[c].astype(str)
        values = [list(df.columns)] + df.values.tolist()
        try:
            ws = sh.worksheet(name)
            ws.clear()
            ws.resize(rows=len(values) + 5, cols=len(df.columns) + 2)
        except gspread.WorksheetNotFound:
            ws = sh.add_worksheet(title=name, rows=len(values) + 5, cols=len(df.columns) + 2)
        ws.update(range_name="A1", values=values)
        written.append(f"{name} ({len(df)} rows)")
    return written


# ----------------------------------------------------------------------------
# CLI: populate a test sheet from the local sample xlsx files
# ----------------------------------------------------------------------------
def _cli():
    import argparse
    import os

    p = argparse.ArgumentParser(description="Push local sample data into a Google Sheet.")
    p.add_argument("action", choices=["upload"], help="upload = push sample_*.xlsx to the sheet")
    p.add_argument("--url", required=True, help="Google Sheet URL or key")
    p.add_argument("--creds", required=True, help="path to service-account JSON key")
    args = p.parse_args()

    data_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), "data")
    frames = {
        "bookings": pd.read_excel(os.path.join(data_dir, "sample_bookings.xlsx")),
        "partners": pd.read_excel(os.path.join(data_dir, "sample_partners.xlsx")),
        "leads": pd.read_excel(os.path.join(data_dir, "sample_leads.xlsx")),
    }
    client = connect(args.creds)
    print("Service account:", service_account_email(args.creds))
    written = push_dataframes(client, args.url, frames)
    print("Wrote tabs:", ", ".join(written))
    print("Done. Now read it back from the app.")


if __name__ == "__main__":
    _cli()
